### PR TITLE
FFFR: Update submodule.

### PR DESCRIPTION
**Pull request by Sibras**

### CODE REVIEW

**Comment by anibali** [comment]
For future reference, the main purpose of this PR is to fix frames from certain files (eg `M100FS_Final_WorldChampionshipTrials2019.MP4`) reading out of order when using the FFFR backend. Also, the current version of FFFReader being used is from Jul 30, 2019 (https://github.com/Sibras/FFFrameReader/tree/f16b320aab56109c9f8138966881d7106a7343ea).

---

I've checked out the branch locally and unfortunately the problem persists. I do have some console messages now, however:

```
st: 0 edit list: 1 Missing key frame while searching for timestamp: 1000
st: 0 edit list 1 Cannot find an index entry before timestamp: 1000.
```

This output appears as soon as I open the file and read the first frame (possible seeking to timestamp 0 first).

I'm also noticing that a lot of other video files which work just fine are now printing this message: `Cannot get a new frame, End of file has been reached`. From what I can see this doesn't seem to cause any decoding issues other than being annoying.

**Comment by Multihuntr** [comment]
For reference, the

```
st: 0 edit list: 1 Missing key frame while searching for timestamp: 1000
st: 0 edit list 1 Cannot find an index entry before timestamp: 1000.
```

messages are also printed out by ffprobe on this file. I suppose it's an error from within `ffmpeg`.

**Comment by Sibras** [comment]
> st: 0 edit list: 1 Missing key frame while searching for timestamp: 1000
> st: 0 edit list 1 Cannot find an index entry before timestamp: 1000.

This is from FFmpeg as previously stated. It can be ignored as errors such as this are corrected for afterwards.

You can change the log level if you want to silence such messages.

**Comment by Sibras** [comment]
The PR has been updated with an updated version of FFFR

**Comment by anibali** [comment]
I can see that you've definitely fixed _something_, since another video file that we were having issues with now works (that one just had a weird issue with missing the first 2 frames). However, the video that you've been working with (`M100FS_Final_WorldChampionshipTrials2019.MP4`) still reads frames out of order.

## Analysis

I now  have a way to quickly switch between backends while visualising frames. Using this tool, I was able to analyse the behaviour of FFFR a bit better. This analysis was performed by seeking to and reading frames, using the NVDEC backend as the reference point for correctness (since this reads all of the frames in order).  Experiments are with `m_bufferLength = 2`.

The pattern I've found is that the video alternates between 18 jumbled frames and 6 correct frames. So the first 18 frames of the video are jumbled, the next 6 agree with NVDEC, the next 18 are jumbled, and so on. It also looks to me like the jumbled frames are always further into the future compared to what NVDEC shows.

Here's an example of FFFR's behaviour from somewhere in the middle of the video.

* The range of frames 1506--1511 agree between the FFFR and NVDEC backends.
* When I seek to 1512, FFFR jumps ahead a lot (we are now ahead of NVDEC)
* When I seek to 1513, FFFR jumps back a little (we are still ahead of NVDEC)
* When I seek to 1514, FFFR advances (we are still ahead of NVDEC)
* When I seek to 1515, FFFR advances (we are still ahead of NVDEC)
* When I seek to 1516, FFFR jumps back a little (we are still ahead of NVDEC)
* When I seek to 1517, FFFR advances (we are still ahead of NVDEC)
* When I seek to 1518, FFFR advances (we are still ahead of NVDEC)
* When I seek to 1519, FFFR jumps back a little (we are still ahead of NVDEC)
...
* The range of frames 1530--1535 agree between the FFFR and NVDEC backends.

In terms of log output, here's what it looks like seeking and reading frame 0 (which is incorrect):

```
[PLAYER] Seeking to frame: 0
seek- Seek requested: 0
decodeNextBlock- Received packet: -1000, -20000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 1, 20000
decodeNextFrames- Flushing till time: 0, 0
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 2, 40000
decodeNextFrames- Flushing till time: 0, 0
decodeNextFrames- Dumping frame due to flush time: 2, 40000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 0, 0
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 3, 60000
decodeNextFrames- Flushing till time: 0, 0
decodeNextFrames- Dumping frame due to flush time: 3, 60000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 1000, 20000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 4, 80000
decodeNextFrames- Flushing till time: 0, 0
decodeNextFrames- Dumping frame due to flush time: 4, 80000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 2000, 40000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 5, 100000
decodeNextFrames- Flushing till time: 0, 0
decodeNextFrames- Dumping frame due to flush time: 5, 100000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 3000, 60000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 6, 120000
decodeNextFrames- Flushing till time: 0, 0
decodeNextFrames- Dumping frame due to flush time: 6, 120000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 4000, 80000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 8, 160000
decodeNextFrames- Flushing till time: 0, 0
decodeNextFrames- Dumping frame due to flush time: 8, 160000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 5000, 100000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 6000, 120000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 0, 0
decodeNextFrames- Flushing till time: 0, 0
decodeNextFrames- Found flush time: 0, 0
decodeNextFrames- Decoder returned EAGAIN/EOF
getNextFrame- Retrieved frame: 0
```

And here's frame 18 (which is correct):

```
[PLAYER] Seeking to frame: 18
seek- Seek requested: 360000
decodeNextBlock- Received packet: -1000, -20000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 20, 400000
decodeNextFrames- Flushing till time: 18, 360000
decodeNextFrames- Dumping frame due to flush time: 20, 400000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 0, 0
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 21, 420000
decodeNextFrames- Flushing till time: 18, 360000
decodeNextFrames- Dumping frame due to flush time: 21, 420000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 1000, 20000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 22, 440000
decodeNextFrames- Flushing till time: 18, 360000
decodeNextFrames- Dumping frame due to flush time: 22, 440000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 2000, 40000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 23, 460000
decodeNextFrames- Flushing till time: 18, 360000
decodeNextFrames- Dumping frame due to flush time: 23, 460000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 3000, 60000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 24, 480000
decodeNextFrames- Flushing till time: 18, 360000
decodeNextFrames- Dumping frame due to flush time: 24, 480000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 4000, 80000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 26, 520000
decodeNextFrames- Flushing till time: 18, 360000
decodeNextFrames- Dumping frame due to flush time: 26, 520000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 5000, 100000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 6000, 120000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 0, 0
decodeNextFrames- Flushing till time: 18, 360000
decodeNextFrames- Dumping frame due to flush time: 0, 0
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 7000, 140000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 1, 20000
decodeNextFrames- Flushing till time: 18, 360000
decodeNextFrames- Dumping frame due to flush time: 1, 20000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 8000, 160000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 2, 40000
decodeNextFrames- Flushing till time: 18, 360000
decodeNextFrames- Dumping frame due to flush time: 2, 40000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 9000, 180000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 3, 60000
decodeNextFrames- Flushing till time: 18, 360000
decodeNextFrames- Dumping frame due to flush time: 3, 60000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 10000, 200000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 4, 80000
decodeNextFrames- Flushing till time: 18, 360000
decodeNextFrames- Dumping frame due to flush time: 4, 80000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 11000, 220000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 5, 100000
decodeNextFrames- Flushing till time: 18, 360000
decodeNextFrames- Dumping frame due to flush time: 5, 100000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 12000, 240000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 6, 120000
decodeNextFrames- Flushing till time: 18, 360000
decodeNextFrames- Dumping frame due to flush time: 6, 120000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 13000, 260000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 7, 140000
decodeNextFrames- Flushing till time: 18, 360000
decodeNextFrames- Dumping frame due to flush time: 7, 140000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 14000, 280000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 8, 160000
decodeNextFrames- Flushing till time: 18, 360000
decodeNextFrames- Dumping frame due to flush time: 8, 160000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 15000, 300000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 9, 180000
decodeNextFrames- Flushing till time: 18, 360000
decodeNextFrames- Dumping frame due to flush time: 9, 180000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 16000, 320000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 10, 200000
decodeNextFrames- Flushing till time: 18, 360000
decodeNextFrames- Dumping frame due to flush time: 10, 200000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 17000, 340000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 11, 220000
decodeNextFrames- Flushing till time: 18, 360000
decodeNextFrames- Dumping frame due to flush time: 11, 220000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 18000, 360000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 12, 240000
decodeNextFrames- Flushing till time: 18, 360000
decodeNextFrames- Dumping frame due to flush time: 12, 240000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 19000, 380000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 13, 260000
decodeNextFrames- Flushing till time: 18, 360000
decodeNextFrames- Dumping frame due to flush time: 13, 260000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 20000, 400000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 14, 280000
decodeNextFrames- Flushing till time: 18, 360000
decodeNextFrames- Dumping frame due to flush time: 14, 280000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 21000, 420000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 15, 300000
decodeNextFrames- Flushing till time: 18, 360000
decodeNextFrames- Dumping frame due to flush time: 15, 300000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 22000, 440000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 16, 320000
decodeNextFrames- Flushing till time: 18, 360000
decodeNextFrames- Dumping frame due to flush time: 16, 320000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 23000, 460000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 17, 340000
decodeNextFrames- Flushing till time: 18, 360000
decodeNextFrames- Dumping frame due to flush time: 17, 340000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 18, 360000
decodeNextFrames- Flushing till time: 18, 360000
decodeNextFrames- Found flush time: 18, 360000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 24000, 480000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 19, 380000
getNextFrame- Retrieved frame: 360000
```

## One more thing

In order to get this to compile on Linux, I have to comment out the following line in `CMakeLists.txt`: https://github.com/Sibras/FFFrameReader/blob/587a6948e02fbb3add3a075f907f9cbf0a54e659/CMakeLists.txt#L155. It's not just the lack of a space between the options, the compiler will complain if either flag is present.

**Comment by anibali** [comment]
Important follow-up: with `m_bufferLength = 18`, everything seems to work just fine (the ordering of frames is correct).

EDIT: even smaller values like `m_bufferLength = 8` or even `4` appear to work also.

**Comment by Sibras** [comment]
Updated to fix "M100FS_Final_WorldChampionshipTrials2019.MP4"

Although locally I wasn't getting:

> decodeNextFrames- Frame did not contain valid timestamp

Are you using some sort of resizing or cropping during those tests?

**Comment by anibali** [comment]
> Are you using some sort of resizing or cropping during those tests?

Ah, yes. In order to get things playing back relatively quickly I have been resizing to 720p. I should have mentioned that, sorry.

**Comment by anibali** [comment]
Still can't compile with `-fno-rtti -fno-exceptions`:

```
FAILED: ext/FFFrameReader/CMakeFiles/FfFrameReader.dir/source/FFFRDecoderContext.cpp.o 
/usr/bin/c++   -I../../../ext/FFFrameReader/include -I/usr/local/include -I/usr/local/cuda/targets/x86_64-linux/include -Iext/FFFrameReader -O3 -DNDEBUG -flto -fno-fat-lto-objects -fPIC   -fno-rtti -fno-exceptions -std=gnu++1z -MD -MT ext/FFFrameReader/CMakeFiles/FfFrameReader.dir/source/FFFRDecoderContext.cpp.o -MF ext/FFFrameReader/CMakeFiles/FfFrameReader.dir/source/FFFRDecoderContext.cpp.o.d -o ext/FFFrameReader/CMakeFiles/FfFrameReader.dir/source/FFFRDecoderContext.cpp.o -c ../../../ext/FFFrameReader/source/FFFRDecoderContext.cpp
../../../ext/FFFrameReader/source/FFFRDecoderContext.cpp: In constructor ‘Ffr::DecoderContext::DecoderContext(Ffr::DecoderContext::DecodeType, const std::any&, uint32_t)’:
../../../ext/FFFrameReader/source/FFFRDecoderContext.cpp:112:18: error: exception handling disabled, use -fexceptions to enable
         } catch (...) {
                  ^~~
../../../ext/FFFrameReader/source/FFFRDecoderContext.cpp:126:29: error: ‘const class std::any’ has no member named ‘type’
                 if (context.type() != typeid(CUcontext)) {
                             ^~~~
../../../ext/FFFrameReader/source/FFFRDecoderContext.cpp:126:55: error: cannot use typeid with -fno-rtti
                 if (context.type() != typeid(CUcontext)) {

```

**Comment by anibali** [comment]
Commenting out the CMakeLists.txt line again, I tested reading `M100FS_Final_WorldChampionshipTrials2019.MP4` with tvl-backends-fffr using https://github.com/Sibras/FFFrameReader/commit/4bd21dd315e94cd751d01bcd2aa54743664768bd.

With resizing disabled, the frames are read in the correct order. Tested with `m_bufferLength = 1` and `m_noBufferFlush = true`.

When resizing to 720p, the frames are read in a jumbled order like before. I've tested this using `m_bufferLength = 1`, `m_scale.m_height = 720`, and `m_scale.m_width = 1280`, both with and without `m_noBufferFlush`.

## Debug output

* `m_bufferLength = 1`
* `m_noBufferFlush = true`

### No resize (correct ordering)

```
[DEBUG] video_player: Seeking to frame 1500
seek- Seek requested: 30000000
decodeNextBlock- Received packet: 1487000, 29740000
decodeNextFrames- Flushing till time: 3000, 30000000
decodeNextFrames- Dumping frame due to flush time: 3004, 30040000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 1488000, 29760000
decodeNextFrames- Flushing till time: 3000, 30000000
decodeNextFrames- Dumping frame due to flush time: 2976, 29760000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 1489000, 29780000
decodeNextFrames- Flushing till time: 3000, 30000000
decodeNextFrames- Dumping frame due to flush time: 2978, 29780000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 1490000, 29800000
decodeNextFrames- Flushing till time: 3000, 30000000
decodeNextFrames- Dumping frame due to flush time: 2980, 29800000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 1491000, 29820000
decodeNextFrames- Flushing till time: 3000, 30000000
decodeNextFrames- Dumping frame due to flush time: 2982, 29820000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 1492000, 29840000
decodeNextFrames- Flushing till time: 3000, 30000000
decodeNextFrames- Dumping frame due to flush time: 2984, 29840000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 1493000, 29860000
decodeNextFrames- Flushing till time: 3000, 30000000
decodeNextFrames- Dumping frame due to flush time: 2986, 29860000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 1494000, 29880000
decodeNextFrames- Flushing till time: 3000, 30000000
decodeNextFrames- Dumping frame due to flush time: 2988, 29880000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 1495000, 29900000
decodeNextFrames- Flushing till time: 3000, 30000000
decodeNextFrames- Dumping frame due to flush time: 2990, 29900000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 1496000, 29920000
decodeNextFrames- Flushing till time: 3000, 30000000
decodeNextFrames- Dumping frame due to flush time: 2992, 29920000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 1497000, 29940000
decodeNextFrames- Flushing till time: 3000, 30000000
decodeNextFrames- Dumping frame due to flush time: 2994, 29940000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 1498000, 29960000
decodeNextFrames- Flushing till time: 3000, 30000000
decodeNextFrames- Dumping frame due to flush time: 2996, 29960000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 1499000, 29980000
decodeNextFrames- Flushing till time: 3000, 30000000
decodeNextFrames- Dumping frame due to flush time: 2998, 29980000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 1500000, 30000000
decodeNextFrames- Flushing till time: 3000, 30000000
decodeNextFrames- Found flush time: 3000, 30000000
decodeNextFrames- Decoder returned EAGAIN/EOF
getNextFrame- Retrieved frame: 30000000
```

### Resize to 720p (jumbled ordering)

```
[DEBUG] video_player: Seeking to frame 1500
seek- Seek requested: 30000000
decodeNextBlock- Received packet: 1487000, 29740000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 1501, 30020000
decodeNextFrames- Flushing till time: 1500, 30000000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 1502, 30040000
decodeNextFrames- Flushing till time: 1500, 30000000
decodeNextFrames- Dumping frame due to flush time: 1502, 30040000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 1488000, 29760000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 1503, 30060000
decodeNextFrames- Flushing till time: 1500, 30000000
decodeNextFrames- Dumping frame due to flush time: 1503, 30060000
decodeNextBlock- Received packet: 1489000, 29780000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 1504, 30080000
decodeNextFrames- Flushing till time: 1500, 30000000
decodeNextFrames- Dumping frame due to flush time: 1504, 30080000
decodeNextBlock- Received packet: 1490000, 29800000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 1505, 30100000
decodeNextFrames- Flushing till time: 1500, 30000000
decodeNextFrames- Dumping frame due to flush time: 1505, 30100000
decodeNextBlock- Received packet: 1491000, 29820000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 1508, 30160000
decodeNextFrames- Flushing till time: 1500, 30000000
decodeNextFrames- Dumping frame due to flush time: 1508, 30160000
decodeNextBlock- Received packet: 1492000, 29840000
decodeNextFrames- Decoder returned EAGAIN/EOF
decodeNextBlock- Received packet: 1493000, 29860000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 1488, 29760000
decodeNextFrames- Flushing till time: 1500, 30000000
decodeNextFrames- Dumping frame due to flush time: 1488, 29760000
decodeNextBlock- Received packet: 1494000, 29880000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 1489, 29780000
decodeNextFrames- Flushing till time: 1500, 30000000
decodeNextFrames- Dumping frame due to flush time: 1489, 29780000
decodeNextBlock- Received packet: 1495000, 29900000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 1490, 29800000
decodeNextFrames- Flushing till time: 1500, 30000000
decodeNextFrames- Dumping frame due to flush time: 1490, 29800000
decodeNextBlock- Received packet: 1496000, 29920000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 1491, 29820000
decodeNextFrames- Flushing till time: 1500, 30000000
decodeNextFrames- Dumping frame due to flush time: 1491, 29820000
decodeNextBlock- Received packet: 1497000, 29940000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 1492, 29840000
decodeNextFrames- Flushing till time: 1500, 30000000
decodeNextFrames- Dumping frame due to flush time: 1492, 29840000
decodeNextBlock- Received packet: 1498000, 29960000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 1493, 29860000
decodeNextFrames- Flushing till time: 1500, 30000000
decodeNextFrames- Dumping frame due to flush time: 1493, 29860000
decodeNextBlock- Received packet: 1499000, 29980000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 1494, 29880000
decodeNextFrames- Flushing till time: 1500, 30000000
decodeNextFrames- Dumping frame due to flush time: 1494, 29880000
decodeNextBlock- Received packet: 1500000, 30000000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 1495, 29900000
decodeNextFrames- Flushing till time: 1500, 30000000
decodeNextFrames- Dumping frame due to flush time: 1495, 29900000
decodeNextBlock- Received packet: 1501000, 30020000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 1496, 29920000
decodeNextFrames- Flushing till time: 1500, 30000000
decodeNextFrames- Dumping frame due to flush time: 1496, 29920000
decodeNextBlock- Received packet: 1502000, 30040000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 1497, 29940000
decodeNextFrames- Flushing till time: 1500, 30000000
decodeNextFrames- Dumping frame due to flush time: 1497, 29940000
decodeNextBlock- Received packet: 1503000, 30060000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 1498, 29960000
decodeNextFrames- Flushing till time: 1500, 30000000
decodeNextFrames- Dumping frame due to flush time: 1498, 29960000
decodeNextBlock- Received packet: 1504000, 30080000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 1499, 29980000
decodeNextFrames- Flushing till time: 1500, 30000000
decodeNextFrames- Dumping frame due to flush time: 1499, 29980000
decodeNextBlock- Received packet: 1505000, 30100000
decodeNextFrames- Frame did not contain valid timestamp
decodeNextFrames- Frame did not contain valid timestamp, corrected timestamp: 1500, 30000000
decodeNextFrames- Flushing till time: 1500, 30000000
decodeNextFrames- Found flush time: 1500, 30000000
decodeNextFrames- Decoder returned EAGAIN/EOF
getNextFrame- Retrieved frame: 30000000
```

**Pull request merged**
